### ISSUE TITLE
Error when Web folder isn't present

### ISSUE THREAD

**Issue by dylanyoung-dev** [dylanyoung-dev/sitecore-cdp-serializer#19]
Starting to deploy WEB templates
Directory does not exist
Directory does not exist
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir '/home/runner/work/website/website/cdp-artifacts/templates/web'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/runner/work/website/website/cdp-artifacts/templates/web'
}

**Comment by mhak** [comment]
@dylanyoung-dev this is resolved by the above PR
